-- ============================================
-- DDA Debug Spawn - Diagnostic Version
-- ============================================

local function onFillWorldObjectContextMenu(playerNum, context, worldObjects, test)
    if not getDebug() then return end
    
    local player = getSpecificPlayer(playerNum)
    if not player then return end
    
    local square = nil
    for _, obj in ipairs(worldObjects) do
        if obj:getSquare() then
            square = obj:getSquare()
            break
        end
    end
    
    if not square then return end
    
    local x, y, z = square:getX(), square:getY(), square:getZ()
    
    -- Test 1: No outfit (naked zombie)
    context:addOption("[1] Spawn Naked Zombie", player, function()
        local zombies = addZombiesInOutfit(x, y, z, 1, nil, 0)
        if zombies and zombies:size() > 0 then
            player:Say("Naked zombie spawned!")
        else
            player:Say("Failed!")
        end
    end)
    
    -- Test 4: Our custom Juggernaut
    context:addOption("[4] Spawn Juggernaut (Visual Only)", player, function()
        -- Outfit spawn
        local zombies = addZombiesInOutfit(x, y, z, 1, "Juggernaut", 0)
        if zombies and zombies:size() > 0 then
            player:Say("Juggernaut spawned!")
        else
            player:Say("Juggernaut FAILED (Outfit not found)")
        end
    end)
    

    
    -- Test 5: NeonGhoul (Generated by Fixed Pipeline)
    context:addOption("[5] Spawn NeonGhoul (Auto-Gen)", player, function()
        local zombies = addZombiesInOutfit(x, y, z, 1, "NeonGhoul", 0)
        if zombies and zombies:size() > 0 then
            player:Say("NeonGhoul spawned! Pipeline verified.")
        else
            player:Say("NeonGhoul FAILED")
        end
    end)

    -- Test 6: Abomination (The 100% Automated Test)
    context:addOption("[6] Spawn Abomination (Automated)", player, function()
        local zombies = addZombiesInOutfit(x, y, z, 1, "Abomination", 0)
        if zombies and zombies:size() > 0 then
            player:Say("Abomination spawned! Pipeline 100% Automated.")
        else
            player:Say("Abomination FAILED")
        end
    end)

    -- Test 7: Stalker (Blender MCP Prototype)
    context:addOption("[7] Spawn Stalker (Blender Proto)", player, function()
        local zombies = addZombiesInOutfit(x, y, z, 1, "Stalker", 0)
        if zombies and zombies:size() > 0 then
            player:Say("Stalker spawned!")
        else
            player:Say("Stalker FAILED (Outfit not found)")
        end
    end)
    
    -- [NEW] Trigger Boss Event (Rare Spawn System)
    context:addOption("!!! [DEBUG] TRIGGER RARE TITAN EVENT !!!", player, function()
        print("[DDA] Triggering Rare Titan Event...")
        
        -- Try to load the server script
        local success, err = pcall(function()
            local RareSpawnEvent = require "DDA/RareSpawnEvent"
            if RareSpawnEvent then
                 RareSpawnEvent.ForceSpawn()
                 player:Say("Titan Event Triggered! Do you hear them?")
            else
                 print("Could not require RareSpawnEvent")
            end
        end)
        
        if not success then
             print("[DDA] Error: " .. tostring(err))
             player:Say("Error triggering event")
        end
    end)
    
    -- Debug: List all available outfits
    context:addOption("[DEBUG] List Outfits in Console", player, function()
        print("[DDA] === LISTING ALL OUTFITS ===")
        local outfitManager = getOutfitManager and getOutfitManager()
        if outfitManager then
            local maleOutfits = outfitManager:getMaleOutfits()
            if maleOutfits then
                print("[DDA] Male outfits count: " .. tostring(maleOutfits:size()))
                for i = 0, math.min(20, maleOutfits:size() - 1) do
                    local outfit = maleOutfits:get(i)
                    if outfit then
                        print("  - " .. tostring(outfit:getName()))
                    end
                end
            end
        end
        player:Say("Check console for outfit list")
    end)
end

Events.OnFillWorldObjectContextMenu.Add(onFillWorldObjectContextMenu)

print("[DDA] Boss Debug Script loaded")
